orgpark/fym_mobile

.flowconfig, package.json
- 0.30에서 0.31로 버전 변경
- Release Note : https://github.com/facebook/react-native/releases/tag/v0.31.0
=> Bump RN version to 0.30

app/App.js, app/Intro.js, package.json
=> Integrate router-flux

.babelrc, app/App.js, app/Intro.js, app/actions/actionTypes.js, app/actions/index.js, app/configureStore.js, app/reducers/index.js, index.android.js, index.ios.js, package.json
- redux 관련 package 정의 및 기본 골격 생성
- router-flux를 적용하여 page navigation 골격 생성
=> Integrate redux and router-flux

app/App.js, app/Hot99.js, app/actions/actionTypes.js, app/actions/index.js, app/reducers/index.js, ios/FeedYourMusic/Info.plist
=> Implement Hot99 chart

android/app/build.gradle, android/app/src/main/java/com/feedyourmusic/MainApplication.java, android/settings.gradle, package.json
- `package.json`에 react-native-player 명시
- Android 관련 dependency 설정
=> Add react-native-player and set native dependency

android/app/src/main/AndroidManifest.xml, ios/FeedYourMusic/Info.plist
=> Disable landscape mode

app/components/Hot99.js, app/components/Player.js, app/components/TabIcon.js, app/containers/App.js
- Tabs : New, Populr, Mentor's pick, Playlist, My Music
- Remove listeners after unmounting components
=> Rearrange tab items and fix warning

app/components/Divider.js, app/components/FeedbackView.js, app/components/Player.js
- FeedbackView 구현
- Divider 컴포넌트 추가
=> Implement FeedbackView and add divider component

app/components/LoginView.js
- 로그인 화면에 Skip 버튼 추가
- 일단 디버깅 용인데 계속 사용할 수도 있음
=> Add an anchor to skip login view

app/actions/playlist.js, app/components/PopularTracks.js
- Track 을 추가할 때 마지막이 누락된 채로 저장됨
- playlist가 업데이트 되기전에 저장을 시도
- 트랙을 추가하는 순간에 디바이스에 리스트를 저장하도록 수정
=> Fix incomplete save for playlist

app/components/NewTracks.js, app/components/PopularTracks.js, app/containers/App.js
- Add this.props to properly access track info
- Change entry point to explore page
=> Fix undefined error and change entry point

.gitignore, android/app/build.gradle
- keystore file is ignored
- Set signingConfig for release apk
=> Setup environment to generate the release APK

ios/FeedYourMusic.xcodeproj/project.pbxproj
- ReactAudio를 iOS 에서 사용하기 위한 환경 설정
- Facebook SDK가 존재하는 폴더 변경
=> Add ReactAudio configuration for iOS and more

package.json
=> Bump RN version to 0.32.0

app/components/LoginView.js, app/components/Player.js, app/components/Playlist.js, app/components/StickyMiniPlayer.js, app/containers/App.js, app/containers/HomeContainer.js, app/reducers/player.js
- 하단 TabBar 상단에 붙여서 표기
- 하기의 정보를 표기
- 썸네일
- 곡명
- 래퍼 이름
- play / pause 상태
- 재생목록 진입을 위한 버튼
- 재생 진행 상태
- 재생 목록이 비었으면 해당 상태에 필요한 정보를 표기 및 각 버튼을 `disable` 로 변경
=> Implement stickyminiplayer

app/actions/player.js, app/actions/playlist.js, app/components/NewTracks.js, app/components/ParallaxView.js, app/components/PopularTracks.js
- `currentTrackIndex` 설정 조건에 오류
- `true`, `false`가 아닌 0보다 크거나 같은 경우로 수정
=> Fix logic to check index to play

app/components/CoverView.js
- instructor 정보가 없는 경우에 대한 처리 추가
- CoverView가 화면 Width 만큼 적용되지 않는 경우에 대한 수정
=> Fix issues related to CoverView

app/components/MentorPick.js, app/components/NewTracks.js, app/components/PopularTracks.js, app/containers/HomeContainer.js
- Show activity indicator until fetch operation is done
=> Attach activity indicator to each list page

app/components/ActivityView.js, app/components/BugReportButton.js, app/containers/ActivityContainer.js, app/containers/MainContainer.js, assets/mock_activity.json
- 더미 json 파일을 읽어서 리스트 생성 후에 표시
- 향후 서버쪽과 정합시에 수정 필요
=> Implement ActivityView

app/actions/player.js, app/actions/playlist.js, app/components/Player.js, app/components/Playlist.js, app/components/StickyMiniPlayer.js, app/components/utils.js, app/containers/App.js, app/containers/PlaylistContainer.js
- Fixed incorrect direction of transition
- Now we store currrent track index so that user can continue
listening previous track when app is launched
=> Fix transition error and store current track index

app/components/LoginView.js, app/components/SettingsView.js, app/components/UserView.js, app/containers/App.js, app/containers/UserContainer.js, app/utils/facebookAPI.js, package.json
- Refactored scenes to implement dynamic routing
- Updated RNRF package
=> Refactor scenes

app/components/Player.js, app/components/StickyMiniPlayer.js
- songs can be controlled from now playing & by apple earbuds
=> - fix ios player remote control issue (play/pause, playing next/prev songs)

app/components/BottomSheet.js, app/components/BottomSheetItem.js, app/components/Player.js, app/containers/PlayerContainer.js
- BottomSheet/Item 구현
- Player에서 more 버튼 눌렀을 때 trigger 됨
=> Implement bottomsheet

app/components/Player.js, app/components/PlayerTabBar.js, app/components/StickyMiniPlayer.js, app/containers/App.js
- Change custom icon button to vector icon button
- Fix error to play track correctly in player scene
- Prevent swipe back gesture in player scene
=> Refactor player kyo

app/components/ActivityView.js, app/components/ArtistView.js, app/components/BottomSheet.js, app/components/BottomSheetItem.js, app/components/ParallaxView.js, app/components/PlayerTabBar.js, app/components/StickyMiniPlayer.js, app/components/TrackList.js, app/store/configureStore.js
- Implement ArtistView
- Add TrackList component for better reusability
- Prevent slow transition by disabling react-logger on dev build
=> Implement artist view and add some other stuff
